import { Platform } from "react-native";
import * as Notifications from "expo-notifications";

/**
 * Android binds a sound to a notification channel when the channel is created and never changes it
 * afterwards, so "the turn succeeded" and "the turn failed" cannot share a channel. Each outcome gets
 * its own channel with its own tone, generated by `scripts/make-notification-sounds.ts` into
 * `android/app/src/main/res/raw`.
 */
const SUCCESS_CHANNEL = "opencode-turn-success";
const FAILURE_CHANNEL = "opencode-turn-failure";

export type TurnOutcome = "success" | "failure";

let configured: Promise<void> | undefined;

// Without a handler expo-notifications has no behaviour to apply and drops the notification
// instead of presenting it, so this has to be registered once, as early as possible.
Notifications.setNotificationHandler({
  handleNotification: async () => ({
    shouldShowAlert: true,
    shouldShowBanner: true,
    shouldShowList: true,
    shouldPlaySound: true,
    shouldSetBadge: false,
  }),
});

export function configureNotifications() {
  configured ??= (async () => {
    if (Platform.OS === "android") {
      await Notifications.setNotificationChannelAsync(SUCCESS_CHANNEL, {
        name: "Respuesta del agente",
        importance: Notifications.AndroidImportance.HIGH,
        sound: "success",
        vibrationPattern: [0, 180, 120, 180],
        lightColor: "#7C5CFF",
      });
      await Notifications.setNotificationChannelAsync(FAILURE_CHANNEL, {
        name: "Fallo del agente",
        importance: Notifications.AndroidImportance.HIGH,
        sound: "error",
        vibrationPattern: [0, 450, 150, 450],
        lightColor: "#FF4D4F",
      });
      console.log("[notificaciones] canales creados", SUCCESS_CHANNEL, FAILURE_CHANNEL);
    }
    const current = await Notifications.getPermissionsAsync();
    console.log("[notificaciones] permiso:", current.status);
    // Android 13+ can no longer post notifications without a runtime grant.
    if (current.status !== "granted") await Notifications.requestPermissionsAsync();
  })().catch((cause) => {
    console.warn("[notificaciones] fallo al configurar", cause);
  });
  return configured;
}

function previewOf(text: string | undefined) {
  const clean = (text ?? "").replace(/\s+/g, " ").trim();
  if (!clean) return undefined;
  return clean.length > 140 ? `${clean.slice(0, 139)}…` : clean;
}

export async function notifyTurnFinished(input: {
  sessionTitle: string;
  outcome: TurnOutcome;
  preview?: string;
  errorText?: string;
}) {
  await configureNotifications();
  const failure = input.outcome === "failure";
  try {
    const id = await Notifications.scheduleNotificationAsync({
      content: {
        title: failure ? `Fallo · ${input.sessionTitle}` : input.sessionTitle,
        body: failure
          ? previewOf(input.errorText) ?? "La ejecucion del agente termino con un error"
          : previewOf(input.preview) ?? "Respuesta lista",
        data: { sessionTitle: input.sessionTitle, outcome: input.outcome },
        ...(Platform.OS === "android" ? { channelId: failure ? FAILURE_CHANNEL : SUCCESS_CHANNEL } : {}),
      },
      trigger: null,
    });
    console.warn("[notificaciones] agendada id=" + id + " canal=" + (failure ? FAILURE_CHANNEL : SUCCESS_CHANNEL));
  } catch (cause) {
    // A missing POST_NOTIFICATIONS grant or a killed process must never break the watcher.
    console.warn("[notificaciones] error al agendar", cause);
  }
}
